import Head from 'next/head';

import Skeleton from '@/components/messageSkeleton';
import AllPosts from '@/components/AllPosts';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Twity</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="my-2 text-lg font-medium">
				<h2>See what other people are saying</h2>
				<AllPosts />
			</div>
		</div>
	);
}
